development:
  adapter: postgresql
  encoding: unicode
  database: runbookapp_development
  pool: 5
  host: localhost
  username: jwo

test:
  adapter: postgresql
  encoding: unicode
  database: runbookapp_test
  pool: 5
  host: localhost
  username: jwo
